server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: r2dbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 2
      max-size: 5

# these properties need to be well organized across the different ENV
app:
  security:
    jwt:
      access-token-expiration: 86400000 #24 hours for local testing #900000 # 15 minutes
      refresh-token-expiration: 604800000 # 7 days
    disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail
