services:
  postgres:
    container_name: order-service
    image: postgres:17.5
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres:
