spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
         webflux:
           routes:
             - id: auth-service
               uri: http://auth-service:8081
               predicates:
                 - Path=/api/v1/auth/**
             - id: order-service
               uri: http://order-service:8082
               predicates:
                 - Path=/api/v1/orders/**
             - id: inventory-service
               uri: http://inventory-service:8083
               predicates:
                 - Path=/api/v1/inventory/**,/api/v1/products/**
             - id: payment-service
               uri: http://payment-service:8084
               predicates:
                 - Path=/api/v1/payments/**

